global using AutoMapper;
global using CommonMormon.Infrastructure.API.Controllers;
global using CommonMormon.Infrastructure.API.Services;
global using CommonMormon.Infrastructure.Shared.DTO;
global using MassTransit;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using ERP.Domain.Model;
global using ERP.Infrastructure;
