﻿@hostname = localhost
@port = 7118
@host = {{hostname}}:{{port}}
@url = https://{{host}}
@contentType = application/json


###获取清单
GET https://localhost:7118/Todo/TodoItem/Query
Content-Type:{{contentType}}
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOUY4Njc0NUMzNjNFRTE3Njk5MzdEMzFGQUY3MUFCIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMxMCIsIm5iZiI6MTY4NjU2MzEyNywiaWF0IjoxNjg2NTYzMTI3LCJleHAiOjE2ODY1NjY3MjcsInNjb3BlIjpbImNvbW1vbm1vcm1vbl9pZGVudGl0eV90b2RvX2FwaSJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6ImNvbW1vbm1vcm1vbl9pZGVudGl0eV90b2RvX2FwaSIsInN1YiI6ImQ1ZGFiMWM4LWQzNDYtNDY4Ny04ZWY0LTQ2MTJmOGM3MDhjNSIsImF1dGhfdGltZSI6MTY4NjU2MzEyNiwiaWRwIjoibG9jYWwiLCJuYW1lIjoiYWRtaW4ifQ.DWkYvhDK6L6DBVYMfLdbPqWicPuubGTfVzqgXZxAOSFZpdPhfBDkzvqBf-TyIGn4vGsi6EJJ8Dz9lHV_AjcvYL3I0-vlX7r5CSRH906OYn2rH1lpxrvMJXuM9am8sNfUQaFfMQegAsCjnQigVLnqS2uw4E7RVSozKrSNv2ia9MH3D_BEG9NWOC5WXkZ3P897rSrLOw7iSAZuOzPYqDd320EEoT0a1yjvl4s486VQLy8vV9u1t-L1xO0q3jR1fA7O4ee0mgQDs4lmCHP9JYIX7OJvcDmOoNo_aFfMHpZBT9GLDgmzLkFNSvgaJUilmTVqwD0vlyUkkVdG1OSfEmNV3Q


###获取授权
POST  https://localhost:7118/auth/token
Content-Type:application/x-www-form-urlencoded

client_id=commonmormon_identity_todo_api&client_secret=994266e8f8437f39b559&grant_type=password&username=zcqiand
&password=Pa$$word123
