﻿@hostname = www.shanyang.store
@port = 7118
@host = {{hostname}}:{{port}}
@url = https://{{host}}
@contentType = application/json

###获取清单
GET https://www.ultranuke.xyz/Todo/TodoItem/Query
Content-Type:{{contentType}}
Authorization: Bearer #Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOUY4Njc0NUMzNjNFRTE3Njk5MzdEMzFGQUY3MUFCIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMxMCIsIm5iZiI6MTY4NjM3MTIxNiwiaWF0IjoxNjg2MzcxMjE2LCJleHAiOjE2ODYzNzQ4MTYsInNjb3BlIjpbImNvbW1vbm1vcm1vbl9pZGVudGl0eV90b2RvX2FwaSJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6ImNvbW1vbm1vcm1vbl9pZGVudGl0eV90b2RvX2FwaSIsInN1YiI6ImQ1ZGFiMWM4LWQzNDYtNDY4Ny04ZWY0LTQ2MTJmOGM3MDhjNSIsImF1dGhfdGltZSI6MTY4NjM3MTIxNiwiaWRwIjoibG9jYWwiLCJuYW1lIjoiYWRtaW4ifQ.LW5GTCwf9I-8IMzTKCZhryTyxn5qCs_W6u1_ANBk5cslMFcl6n4y2_7_KvnLNgQYBbZvc8Oxejmq8vGJUTfFchsdeIFAdhd-xRR33dyQiSmvUjyHDPtbGqlr1GvVIsbSHYfTV6m_IIecopYe678ii5laUzvyijhHiQChzjDM5tSbnvAEuoQEN8cbXynZ-G5Pn7xlTtfD2vAjNbUrdecwiD4hIJFoL90fCZt_eHb3SN6eNhJjLeerRYZjfVX3FDrKWa6vr-KkMpUXsfTQPUEzwBvIKh3CDS0yFYvXDV8y0o8iXLliItsGCGqocPDOKMh8l6njbnKsfQGVrYlltO2-Hg


###获取授权
POST  https://www.ultranuke.xyz/auth/token
Content-Type:application/x-www-form-urlencoded

client_id=commonmormon_identity_todo_api&client_secret=994266e8f8437f39b559&grant_type=password&username=zcqiand
&password=Pa$$word123


###获取清单
GET https://localhost:7225/api/Todo/TodoItem/Query
Content-Type:{{contentType}}
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwOUY4Njc0NUMzNjNFRTE3Njk5MzdEMzFGQUY3MUFCIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMxMCIsIm5iZiI6MTY4NjM2NTgzNiwiaWF0IjoxNjg2MzY1ODM2LCJleHAiOjE2ODYzNjk0MzYsInNjb3BlIjpbImNvbW1vbm1vcm1vbl9pZGVudGl0eV90b2RvX2FwaSJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6ImNvbW1vbm1vcm1vbl9pZGVudGl0eV90b2RvX2FwaSIsInN1YiI6ImQ1ZGFiMWM4LWQzNDYtNDY4Ny04ZWY0LTQ2MTJmOGM3MDhjNSIsImF1dGhfdGltZSI6MTY4NjM2NTgzNSwiaWRwIjoibG9jYWwiLCJuYW1lIjoiYWRtaW4ifQ.CC4V5Wkj1n0mKQ5NqcPXUDoGpe1iUWgYc7eSxeH5DmQ5iF7GR2FeLnObqRtOzu7R8yK8LtThr3oLJwmnzhL-b-pxkwPNZheiPcRQeF6xOdRxUvzID-NW1x3sabkQCukrt78_nEYYmUZsu4ptSHakXrTBWAVFyoxfPafZflYXBj1k83-ig7VAeTqI-gJYn-iK0rYf3XEJZsMWWABy_IRjw9szpXFP4CpUK8GOtZ7mgNonAiB-cdBB7qBayuwboscqnlTWmRjXHUc_usjaQSVFD8p1Rt8HrtE7lrrVEKoj4NwMeucsqLAqOveAVMLnV3bapjREbDhOJjoCQArTBwXkmw


###获取授权
POST  https://localhost:44310/connect/token
Content-Type:application/x-www-form-urlencoded

client_id=commonmormon_identity_todo_api&client_secret=994266e8f8437f39b559&grant_type=password&username=zcqiand
&password=Pa$$word123
